dev: orderdev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: orderclient
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pm208?serverTimezone=GMT
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
server:
  port: 9090
product:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
